
zuul:
  routes:
    book-service:
      path: /book-service/**
      service-id: book-service
    catalog-service:
      path: /catalog-service/**
      service-id: catalog-service
  host:
      socket-timeout-millis: 300000
